using System.Text;
using WorkflowDashboard.Api.Models;

namespace WorkflowDashboard.Api.Services.AgentRunner;

public sealed class WorkflowInputWriter
{
    private const string RelativePath = ".github/copilot/workflow-input.md";
    private static readonly SemaphoreSlim _fileLock = new(1, 1);

    private readonly ILogger<WorkflowInputWriter> _logger;

    public WorkflowInputWriter(ILogger<WorkflowInputWriter> logger)
    {
        _logger = logger;
    }

    public static string GetPath(Repository repo) =>
        Path.Combine(repo.Path, ".github", "copilot", "workflow-input.md");

    /// <summary>
    /// Writes the initial pipeline input file (called at pipeline run start).
    /// </summary>
    public string Write(PipelineRun run, Repository repo, string apiBaseUrl, WorkflowDashboard.Api.Models.Pipeline pipeline, Feature? feature = null)
    {
        var target = GetPath(repo);
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);

        var sb = new StringBuilder();
        sb.AppendLine("# Pipeline Input");
        sb.AppendLine($"> Generated by Workflow Automation Dashboard — {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();
        sb.AppendLine("## Context");
        sb.AppendLine();
        sb.AppendLine("| Key | Value |");
        sb.AppendLine("|-----|-------|");
        sb.AppendLine($"| Pipeline Run ID | `{run.Id}` |");
        sb.AppendLine($"| Pipeline | `{pipeline.Name}` |");
        sb.AppendLine($"| Feature ID | `{run.FeatureId ?? "not yet created"}` |");
        sb.AppendLine($"| Repository path | `{repo.Path}` |");
        sb.AppendLine($"| API base URL | `{apiBaseUrl}` |");
        sb.AppendLine();

        if (feature is not null)
        {
            sb.AppendLine("## Linked Feature");
            sb.AppendLine();
            sb.AppendLine($"**Name:** {feature.Name}");
            if (!string.IsNullOrWhiteSpace(feature.Description))
                sb.AppendLine($"**Description:** {feature.Description}");
            if (!string.IsNullOrWhiteSpace(feature.SpecFolder))
                sb.AppendLine($"**Spec folder:** `{feature.SpecFolder}`");
            sb.AppendLine();
        }

        var tmp = target + ".tmp";
        File.WriteAllText(tmp, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        File.Move(tmp, target, overwrite: true);

        _logger.LogInformation("Wrote pipeline input file: {Path}", target);
        return target;
    }

    /// <summary>
    /// Appends a section to the workflow-input.md file for a pipeline step.
    /// Thread-safe via SemaphoreSlim.
    /// </summary>
    public async Task AppendSection(string filePath, string stepId, int attemptNumber, string? agentSlug, string? nextStepId, string content)
    {
        var header = $"\n\n## [{stepId}] attempt {attemptNumber} — by: {agentSlug ?? "system"} — for: {nextStepId ?? "end"}\n\n{content}";

        await _fileLock.WaitAsync();
        try
        {
            File.AppendAllText(filePath, header, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }
        finally
        {
            _fileLock.Release();
        }
    }

    public void Cleanup(Repository repo)
    {
        var target = GetPath(repo);
        var tmp = target + ".tmp";
        TryDelete(target);
        TryDelete(tmp);
    }

    private void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path))
            {
                File.Delete(path);
                _logger.LogInformation("Removed pipeline input file: {Path}", path);
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to delete pipeline input file {Path} (best-effort).", path);
        }
    }
}
