// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowDashboard.Api.Data;

#nullable disable

namespace WorkflowDashboard.Api.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("WorkflowDashboard.Api.Models.ApprovalRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId");

                    b.HasIndex("StepRunId");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.Feature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecFolder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("backlog");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.Pipeline", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.PipelineRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PipelineId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("Status");

                    b.ToTable("PipelineRuns");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.PipelineStepRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSlug")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId");

                    b.ToTable("PipelineStepRuns");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.Repository", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.ApprovalRequest", b =>
                {
                    b.HasOne("WorkflowDashboard.Api.Models.PipelineRun", "PipelineRun")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowDashboard.Api.Models.PipelineStepRun", "StepRun")
                        .WithMany()
                        .HasForeignKey("StepRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineRun");

                    b.Navigation("StepRun");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.Feature", b =>
                {
                    b.HasOne("WorkflowDashboard.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.PipelineRun", b =>
                {
                    b.HasOne("WorkflowDashboard.Api.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkflowDashboard.Api.Models.Pipeline", "Pipeline")
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowDashboard.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Pipeline");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.PipelineStepRun", b =>
                {
                    b.HasOne("WorkflowDashboard.Api.Models.PipelineRun", "PipelineRun")
                        .WithMany("StepRuns")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineRun");
                });

            modelBuilder.Entity("WorkflowDashboard.Api.Models.PipelineRun", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("StepRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
